version: '3'

services:
  mybot:
    image: nyxordinal/ester-bot:latest
    container_name: mybot
    environment:
      - CRON_EXPRESSION="* * * * *"
      - DISCORD_TOKEN=<your-bot-token>
      - CHANNEL_ID=<your-channel-id>
      - USER_ID=<your-user-id>
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
